
export class MimeType extends Object { constructor(parameters = {}) { super(); this.parameters = parameters;} }

export class MajorMimeType extends MimeType {}
export class MinorMimeType extends MimeType {}

export class StarStar extends MajorMimeType {}

export class Sparql extends StarStar {}
export class ApplicationSparql extends Sparql {}
export class ApplicationSparqlUpdate extends ApplicationSparql {}
export class SparqlResults extends Sparql {}
export class ApplicationSparqlResults extends SparqlResults {}
export class ImageVndDydraSparqlResults extends SparqlResults {}

export class StarSparqlQueryOlogSvgXml extends MinorMimeType {}
export class StarSparqlQueryOlogTex extends MinorMimeType {}
export class StarSparqlQueryOlog extends MinorMimeType {}
export class ApplicationSparqlQueryOlog extends StarSparqlQueryOlog {}
export class ApplicationSparqlQueryOlogSvgXml extends ApplicationSparqlQueryOlog {}
export class ApplicationSparqlQueryOlogTex extends ApplicationSparqlQueryOlog {}
export class StarVndDydraSparqlResultsTraceGraphviz extends MinorMimeType {}
export class StarVndDydraSparqlQueryPlanGraphviz extends MinorMimeType {}
export class StarVndDydraSparqlQueryAlgebraGraphviz extends MinorMimeType {}
export class StarCircosTsv extends MinorMimeType {}
export class StarBoolean extends MinorMimeType {}
export class TextBoolean extends StarBoolean {}
export class StarRelated extends MinorMimeType {}
export class StarXIcon extends MinorMimeType {}
export class ImageXIcon extends StarXIcon {}
export class StarWebp extends MinorMimeType {}
export class ImageWebp extends StarWebp {}
export class StarVndDydraSparqlResultsExecutionGraphvizSvgXml extends MinorMimeType {}
export class StarVndDydraSparqlResultsExecutionGraphvizPng extends MinorMimeType {}
export class StarVndDydraSparqlResultsGraphvizSvgXml extends MinorMimeType {}
export class StarVndDydraSparqlResultsGraphvizPng extends MinorMimeType {}
export class StarVndDydraSparqlResultsGraphvizJpeg extends MinorMimeType {}
export class StarVndDydraSparqlResultsGraphviz extends MinorMimeType {}
export class StarVndDydraSparqlResultsCircosSvgXml extends MinorMimeType {}
export class StarVndDydraSparqlResultsCircosPng extends MinorMimeType {}
export class StarVndDydraSparqlQueryPlanGraphvizSvgXml extends MinorMimeType {}
export class StarVndDydraSparqlQueryAlgebraGraphvizSvgXml extends MinorMimeType {}
export class StarVndDydraSparqlQueryAlgebraGraphvizPng extends MinorMimeType {}
export class StarCircosSvgXml extends MinorMimeType {}
export class StarCircosPng extends MinorMimeType {}
export class StarXNdjson extends MinorMimeType {}
export class StarVndHdt extends MinorMimeType {}
export class StarVndDydraSparqlResultsHtmlParallelcoordinates extends MinorMimeType {}
export class StarVndDydraSparqlResultsHtmlHive extends MinorMimeType {}
export class StarVndDydraSparqlResultsHtmlD3 extends MinorMimeType {}
export class StarVndDydraSparqlResultsHtmlChartRickshaw extends MinorMimeType {}
export class StarVndDydraSparqlResultsHtmlChart extends MinorMimeType {}
export class StarVndDydraSparqlResultsHtmlTable extends MinorMimeType {}
export class StarVndDydraSparqlResultsTraceJson extends MinorMimeType {}
export class StarVndDydraSparqlResultsTrace extends MinorMimeType {}
export class StarVndDydraSparqlResultsExecutionGraphvizPdf extends MinorMimeType {}
export class StarVndDydraSparqlResultsExecutionGraphviz extends MinorMimeType {}
export class StarVndDydraSparqlResultsGraphvizPdf extends MinorMimeType {}
export class StarVndDydraSparqlResultsExecutionJson extends MinorMimeType {}
export class StarVndDydraSparqlResultsExecution extends MinorMimeType {}
export class StarVndDydraSparqlResults extends MinorMimeType {}
export class StarVndDydraSparqlQueryPlan extends MinorMimeType {}
export class StarVndDydraSparqlQueryAlgebraGraphvizPdf extends MinorMimeType {}
export class StarVndDydraSparqlQueryAlgebra extends MinorMimeType {}
export class StarVndDydraSparqlQuery extends MinorMimeType {}
export class StarTurtleStar extends MinorMimeType {}
export class StarTrig extends MinorMimeType {}
export class StarTrix extends MinorMimeType {}
export class StarSse extends MinorMimeType {}
export class ApplicationSse extends StarSse {}
export class StarSql extends MinorMimeType {}
export class StarSparqlUpdate extends MinorMimeType {}
export class StarSparqlResultsXml extends MinorMimeType {}
export class StarSparqlResultsTrace extends MinorMimeType {}
export class StarSparqlResultsTermNumber extends MinorMimeType {}
export class StarSparqlResultsSseStream extends MinorMimeType {}
export class StarSparqlResultsSsbStream extends MinorMimeType {}
export class StarSparqlResultsSsb extends MinorMimeType {}
export class StarSparqlResultsJsonColumnsStreaming extends MinorMimeType {}
export class StarSparqlResultsJsonColumns extends MinorMimeType {}
export class StarSparqlResultsJsonp extends MinorMimeType {}
export class StarSparqlResultsJson extends MinorMimeType {}
export class StarSparqlResultsExecution extends MinorMimeType {}
export class StarSparqlResultsCircos extends MinorMimeType {}
export class StarSparqlResults extends MinorMimeType {}
export class StarSparqlQueryGraphviz extends MinorMimeType {}
export class StarSparqlQuerySsl extends MinorMimeType {}
export class StarSparqlQuerySse extends MinorMimeType {}
export class StarSparqlQueryJson extends MinorMimeType {}
export class StarSparqlQueryCascalog extends MinorMimeType {}
export class StarSparqlQueryPlan extends MinorMimeType {}
export class StarSparqlQueryExecution extends MinorMimeType {}
export class StarSparqlQueryAlgebra extends MinorMimeType {}
export class StarJsonQuery extends MinorMimeType {}
export class StarSparqlQuery extends MinorMimeType {}
export class StarSparql extends MinorMimeType {}
export class ImageSparql extends StarSparql {}
export class ImageSparqlQuery extends ImageSparql {}
export class StarRdfThrift extends MinorMimeType {}
export class StarThrift extends MinorMimeType {}
export class ApplicationThrift extends StarThrift {}
export class StarRdfJson extends MinorMimeType {}
export class StarLdfNQuads extends MinorMimeType {}
export class StarLdfNTriples extends MinorMimeType {}
export class StarNQuads extends MinorMimeType {}
export class StarNTriples extends MinorMimeType {}
export class StarLdf extends MinorMimeType {}
export class ApplicationLdf extends StarLdf {}
export class ApplicationLdfNQuads extends ApplicationLdf {}
export class ApplicationLdfNTriples extends ApplicationLdf {}
export class StarLdJson extends MinorMimeType {}
export class StarLinkFormat extends MinorMimeType {}
export class ApplicationLinkFormat extends StarLinkFormat {}
export class StarJavascript extends MinorMimeType {}
export class ApplicationJavascript extends StarJavascript {}
export class ApplicationSparqlResultsJsonp extends ApplicationSparqlResults {}
export class StarGzip extends MinorMimeType {}
export class StarGraphql extends MinorMimeType {}
export class StarBgpSse extends MinorMimeType {}
export class StarCxt extends MinorMimeType {}
export class StarBgp extends MinorMimeType {}
export class ApplicationBgp extends StarBgp {}
export class StarVndGraphvizSvgXml extends MinorMimeType {}
export class StarVndGraphvizPng extends MinorMimeType {}
export class StarVndGraphvizJpeg extends MinorMimeType {}
export class StarVndGraphvizPdf extends MinorMimeType {}
export class StarCircos extends MinorMimeType {}
export class StarSexp extends MinorMimeType {}
export class ApplicationSexp extends StarSexp {}
export class StarXGraphviz extends MinorMimeType {}
export class StarVndGraphviz extends MinorMimeType {}
export class StarTurtle extends MinorMimeType {}
export class StarMarkdown extends MinorMimeType {}
export class TextMarkdown extends StarMarkdown {}
export class StarHtmlRdfa extends MinorMimeType {}
export class StarHtml extends MinorMimeType {}
export class TextHtml extends StarHtml {}
export class TextHtmlRdfa extends TextHtml {}
export class StarXhtml extends MinorMimeType {}
export class TextXhtml extends StarXhtml {}
export class StarEventStream extends MinorMimeType {}
export class TextEventStream extends StarEventStream {}
export class StarCsv extends MinorMimeType {}
export class TextCsv extends StarCsv {}
export class StarSvgXml extends MinorMimeType {}
export class StarSvg extends MinorMimeType {}
export class ImageSvg extends StarSvg {}
export class ImageSvgXml extends ImageSvg {}
export class ImageCircosSvgXml extends ImageSvgXml {}
export class ImageVndDydraSparqlResultsCircosSvgXml extends ImageCircosSvgXml {}
export class ImageVndGraphvizSvgXml extends ImageSvgXml {}
export class ImageVndDydraSparqlResultsExecutionGraphvizSvgXml extends ImageVndGraphvizSvgXml {}
export class ImageVndDydraSparqlResultsGraphvizSvgXml extends ImageVndGraphvizSvgXml {}
export class ImageVndDydraSparqlQueryPlanGraphvizSvgXml extends ImageVndGraphvizSvgXml {}
export class ImageVndDydraSparqlQueryAlgebraGraphvizSvgXml extends ImageVndGraphvizSvgXml {}
export class StarPng extends MinorMimeType {}
export class ImagePng extends StarPng {}
export class ImageCircosPng extends ImagePng {}
export class ImageVndDydraSparqlResultsCircosPng extends ImageCircosPng {}
export class ImageVndGraphvizPng extends ImagePng {}
export class ImageVndDydraSparqlResultsExecutionGraphvizPng extends ApplicationSparqlResults {}
export class ImageVndDydraSparqlResultsGraphvizPng extends ApplicationSparqlResults {}
export class ImageVndDydraSparqlQueryAlgebraGraphvizPng extends ImageVndGraphvizPng {}
export class StarJpeg extends MinorMimeType {}
export class StarTabSeparatedValues extends MinorMimeType {}
export class TextTabSeparatedValues extends StarTabSeparatedValues {}
export class TextCircosTsv extends TextTabSeparatedValues {}
export class StarFormData extends MinorMimeType {}
export class MultipartFormData extends StarFormData {}
export class StarXWwwFormUrlencoded extends MinorMimeType {}
export class StarRdfXml extends MinorMimeType {}
export class StarXhtmlRdfa extends MinorMimeType {}
export class StarXhtmlXml extends MinorMimeType {}
export class StarXml extends MinorMimeType {}
export class TextXml extends StarXml {}
export class StarPdf extends MinorMimeType {}
export class ApplicationPdf extends StarPdf {}
export class ApplicationVndGraphvizPdf extends ApplicationPdf {}
export class ApplicationVndDydraSparqlResultsExecutionGraphvizPdf extends ApplicationSparqlResults {}
export class ApplicationVndDydraSparqlResultsGraphvizPdf extends ApplicationSparqlResults {}
export class ApplicationVndDydraSparqlQueryAlgebraGraphvizPdf extends ApplicationVndGraphvizPdf {}
export class StarOctetStream extends MinorMimeType {}
export class StarN3 extends MinorMimeType {}
export class StarJson extends MinorMimeType {}
export class ApplicationJson extends StarJson {}
export class ApplicationXNdjson extends ApplicationJson {}
export class ApplicationVndDydraSparqlResultsTraceJson extends ApplicationSparqlResults {}
export class ApplicationVndDydraSparqlResultsExecutionJson extends ApplicationSparqlResults {}
export class ApplicationSparqlResultsJsonColumnsStreaming extends ApplicationSparqlResults {}
export class ApplicationSparqlResultsJsonColumns extends ApplicationSparqlResults {}
export class ApplicationSparqlResultsJson extends ApplicationSparqlResults {}
export class ApplicationSparqlQueryJson extends ApplicationJson {}
export class ApplicationJsonQuery extends ApplicationJson {}
export class StarPlain extends MinorMimeType {}
export class TextPlain extends StarPlain {}
export class Turtle extends TextPlain {}
export class N3 extends TextPlain {}
export class TextN3 extends N3 {}
export class ApplicationN3 extends N3 {}
export class TextStar extends MajorMimeType {}
export class RdfStar extends MajorMimeType {}
export class MultipartStar extends MajorMimeType {}
export class ImageStar extends MajorMimeType {}
export class ApplicationStar extends MajorMimeType {}
export class Ssb extends ApplicationStar {}
export class ApplicationSparqlResultsSsb extends Ssb {}
export class SsbStream extends Ssb {}
export class ApplicationSparqlResultsSsbStream extends SsbStream {}
export class Sse extends ApplicationStar {}
export class ApplicationSparqlQuerySse extends Sse {}
export class ApplicationSparqlQueryCascalog extends Sse {}
export class ApplicationBgpSse extends Sse {}
export class SseStream extends Sse {}
export class ApplicationSparqlResultsSseStream extends SseStream {}
export class ApplicationVndDydraSparqlResultsHtmlParallelcoordinates extends ApplicationSparqlResults {}
export class ApplicationVndDydraSparqlResultsHtmlHive extends ApplicationSparqlResults {}
export class ApplicationVndDydraSparqlResultsHtmlD3 extends ApplicationSparqlResults {}
export class ApplicationVndDydraSparqlResultsHtmlChart extends ApplicationSparqlResults {}
export class ApplicationVndDydraSparqlResultsHtmlChartRickshaw extends ApplicationVndDydraSparqlResultsHtmlChart {}
export class ApplicationVndDydraSparqlResultsHtmlTable extends ApplicationSparqlResults {}
export class ApplicationVndDydraSparqlResults extends ApplicationSparqlResults {}
export class ApplicationSparqlResultsTermNumber extends ApplicationSparqlResults {}
export class SparqlResultsTrace extends SparqlResults {}
export class TextVndDydraSparqlResultsTraceGraphviz extends SparqlResultsTrace {}
export class ApplicationSparqlResultsTrace extends ApplicationSparqlResults {}
export class ApplicationVndDydraSparqlResultsTrace extends ApplicationSparqlResultsTrace {}
export class SparqlResultsExecution extends SparqlResults {}
export class TextVndDydraSparqlResultsExecutionGraphviz extends SparqlResultsExecution {}
export class ImageVndDydraSparqlResultsExecutionGraphviz extends SparqlResultsExecution {}
export class ImageVndDydraSparqlResultsExecution extends SparqlResultsExecution {}
export class ApplicationVndDydraSparqlResultsExecutionGraphviz extends SparqlResultsExecution {}
export class ApplicationSparqlResultsExecution extends ApplicationSparqlResults {}
export class ApplicationVndDydraSparqlResultsExecution extends ApplicationSparqlResultsExecution {}
export class SparqlQuery extends Sparql {}
export class ApplicationSparqlQuery extends SparqlQuery {}
export class ApplicationVndDydraSparqlQuery extends ApplicationSparqlQuery {}
export class ApplicationSparqlQuerySsl extends ApplicationSparqlQuery {}
export class SparqlQueryPlan extends SparqlQuery {}
export class ImageVndDydraSparqlQueryPlan extends SparqlQueryPlan {}
export class ApplicationSparqlQueryPlan extends SparqlQueryPlan {}
export class ApplicationVndDydraSparqlQueryPlan extends ApplicationSparqlQueryPlan {}
export class SparqlQueryExecution extends SparqlQuery {}
export class ApplicationSparqlQueryExecution extends SparqlQueryExecution {}
export class SparqlQueryAlgebra extends SparqlQuery {}
export class ImageVndDydraSparqlQueryAlgebra extends SparqlQueryAlgebra {}
export class ApplicationVndDydraSparqlQueryAlgebra extends SparqlQueryAlgebra {}
export class ApplicationSparqlQueryAlgebra extends SparqlQueryAlgebra {}
export class Query extends StarStar {}
export class ApplicationSql extends Query {}
export class ApplicationGraphql extends Query {}
export class Circos extends StarStar {}
export class ApplicationSparqlResultsCircos extends ApplicationSparqlResults {}
export class TextCircos extends Circos {}
export class ImageCircos extends Circos {}
export class ApplicationCircos extends Circos {}
export class Xml extends StarStar {}
export class ApplicationXml extends Xml {}
export class ApplicationSparqlResultsXml extends ApplicationSparqlResults {}
export class ApplicationXhtmlXml extends ApplicationXml {}
export class ApplicationXhtmlRdfa extends ApplicationXhtmlXml {}
export class Rdf extends StarStar {}
export class RdfJson extends Rdf {}
export class Triples extends Rdf {}
export class TextTurtle extends Triples {}
export class ApplicationVndHdt extends Triples {}
export class ApplicationRdfJson extends Triples {}
export class ApplicationNTriples extends Triples {}
export class ApplicationCxt extends Triples {}
export class Quads extends Triples {}
export class ApplicationTurtleStar extends Quads {}
export class ApplicationTrig extends Quads {}
export class ApplicationTrix extends Quads {}
export class ApplicationRdfThrift extends Quads {}
export class ApplicationNQuads extends Quads {}
export class ApplicationLdJson extends Quads {}
export class ApplicationRdfXml extends Rdf {}
export class Graphviz extends StarStar {}
export class ImageVndDydraSparqlResultsGraphviz extends Graphviz {}
export class ApplicationSparqlQueryGraphviz extends Graphviz {}
export class GraphvizImage extends Graphviz {}
export class GraphvizApplication extends Graphviz {}
export class TextXGraphviz extends Graphviz {}
export class TextVndGraphviz extends Graphviz {}
export class TextVndDydraSparqlResultsGraphviz extends TextVndGraphviz {}
export class TextVndDydraSparqlQueryPlanGraphviz extends TextVndGraphviz {}
export class TextVndDydraSparqlQueryAlgebraGraphviz extends TextVndGraphviz {}
export class Binary extends StarStar {}
export class ApplicationGzip extends Binary {}
export class ImageJpeg extends Binary {}
export class ImageVndGraphvizJpeg extends ImageJpeg {}
export class ImageVndDydraSparqlResultsGraphvizJpeg extends ImageVndGraphvizJpeg {}
export class ApplicationOctetStream extends Binary {}
export class UnsupportedMimeType extends MimeType {}
export class MimeTypeProfile extends MimeType {}